export const ENEMY_TYPES = {
  raider: {
    name: 'Järnsundssoldat',
    hp: 70,
    speed: 2.2,
    range: 40,
    stop: 14,
    damage: 7,
    delay: 1.1,
    color: '#62674e',
    weapon: 'rifle',
  },
  rusher: {
    name: 'Sundsstormare',
    hp: 55,
    speed: 3.4,
    range: 2.4,
    stop: 1.6,
    damage: 13,
    delay: 0.9,
    color: '#997449',
    weapon: 'shotgun',
  },
  marksman: {
    name: 'Järnsundsskytt',
    hp: 50,
    speed: 1.7,
    range: 70,
    stop: 48,
    damage: 19,
    delay: 2.8,
    color: '#994f46',
    weapon: 'scout',
  },
  heavy: {
    name: 'Pansarvakt',
    hp: 155,
    speed: 1.5,
    range: 42,
    stop: 24,
    damage: 5,
    delay: 0.38,
    color: '#4f6575',
    weapon: 'lmg',
  },
  boss: {
    name: 'Belägringsbefäl',
    hp: 900,
    speed: 1.9,
    range: 25,
    stop: 17,
    damage: 38,
    delay: 3,
    color: '#b36f3e',
    weapon: 'lmg',
  },
};
