// Original game interpretations of Swedish service and hunting weapon families.
// Dimensions, damage and timing are gameplay values, not real-world specifications.
export const WEAPONS = {
  rifle: {
    name: 'Bruksbössan · AK4',
    damage: 19,
    delay: 0.25,
    range: 105,
    mag: 24,
    reload: 1.4,
    automatic: true,
    recoil: 0.065,
    sight: 'aperture',
    zoom: 1.4,
  },
  shotgun: {
    name: 'Slaggkastaren · Hagel 12',
    damage: 70,
    delay: 0.85,
    range: 40,
    mag: 6,
    reload: 2.1,
    automatic: false,
    pellets: 7,
    spread: 0.055,
    recoil: 0.13,
    sight: 'iron',
    zoom: 1.2,
  },
  scout: {
    name: 'Dalälvens öga · m/96',
    damage: 65,
    delay: 0.95,
    range: 155,
    mag: 5,
    reload: 1.9,
    automatic: false,
    recoil: 0.09,
    sight: 'scope',
    zoom: 3,
  },
  pistol: {
    name: 'Bergslagspistolen · m/40',
    damage: 27,
    delay: 0.3,
    range: 55,
    mag: 8,
    reload: 1.1,
    automatic: false,
    recoil: 0.045,
    sight: 'iron',
    zoom: 1.2,
  },
  smg: {
    name: 'Kopparsprutan · Kpist m/45',
    damage: 13,
    delay: 0.095,
    range: 65,
    mag: 36,
    reload: 1.7,
    automatic: true,
    spread: 0.018,
    recoil: 0.035,
    sight: 'aperture',
    zoom: 1.25,
  },
  lmg: {
    name: 'Stålregnet · Ksp 58',
    damage: 22,
    delay: 0.13,
    range: 120,
    mag: 60,
    reload: 3.6,
    automatic: true,
    spread: 0.014,
    recoil: 0.08,
    sight: 'aperture',
    zoom: 1.35,
  },
};
